server:
  port: 18081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_sample?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
# mp相关配置
mybatis-plus:
  configuration:
    # 日志实现类，这里选择ibatis的标准日志输出实现类
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置mapper的xml扫描路径
  mapper-locations:
    - classpath*:/com/gitee/olinonee/web/mapper/*.xml
